# [icon]
# prepend_conds = [
# 	{ if = "hidden & dir",  text = "ğŸ‘»" },  # Hidden directories
# 	{ if = "dir",           text = "ğŸ“" },  # Directories
# 	{ if = "!(dir | link)", text = "ğŸ“„" },  # Normal files (not directories or symlinks)
# ]
